### ISSUE TITLE
Unwanted non-breaking spaces in HTML

### ISSUE THREAD

**Issue by ghost** [diogoneves07/bemtvjs#1]
Hey! I am really loving this idea, and am excited to see where it goes going forward!

However, I am encountering an issue with unwanted non-breaking spaces being added into the HTML like so:

![image](https://user-images.githubusercontent.com/108161206/196337957-cd26f047-60ad-47bc-92fc-09ecfdffe64e.png)

Is this a known issue, or is it intentional? And if so, is there a way to remove them?

Thankyou,
Jayman.

**Comment by diogoneves07** [comment]
Hey @jaymanmatthewsdev, Glad you liked the idea!

So this really is a bug.

Currently, we are using "non-breaking" to avoid empty template because we need the component to have at least one Node inserted in the DOM, this shows that it is an "active" component.

Thank you very much for your issue!

Soon I will release a version with the fix.

**Comment by ghost** [comment]
Alright, good to hear!

I encountered another little quirk that exists with list rendering. When I use `.map` on an array, it re-renders the map function many times per second if I try to use `defineProps` within that scope.

Cheers!

**Comment by diogoneves07** [comment]
Could you show the code snippet? this helps to clarify the  quirk

**Comment by ghost** [comment]
I actually removed the code that I had. *facepalm*

But, this was pretty much what it was:

`App component` (this would run three times per tick for some reason.)
```js
return () => `ul[${todos.map(todo => {
  const todoProps = defineProps({ todo });
  return `TodoItem${todoProps}[]`
})}]`
```

`TodoItem component` (this would run once every tick)
```js
return () => `li[${props.todo}]`;
```

I pulled out the `defineProps` into the `todos` array and it seemed to fix the issue (sort of) but it wasn't a great implementation in my opinion, and it didn't allow for dynamicity

**Comment by diogoneves07** [comment]
Avoid adding code that needs to go through some process inside the template,
because the template will be checked for changes, which will cause the code inside it to be reprocessed.

Think of the template as just the place where you only display the results of some process:

```js
const todoItems = todos
  .map((todo) => {
    const todoProps = defineProps({ todo });
    return `TodoItem${todoProps}[]`;
  })
  .join("");

return () => `ul[${todoItems}]`;

```

**Comment by ghost** [comment]
> Avoid adding code that needs to go through some process inside the template, because the template will be checked for changes, which will cause the code inside it to be reprocessed.
> 
> Think of the template as just the place where you only display the results of some process:
> 
> ```js
> const todoItems = todos
>   .map((todo) => {
>     const todoProps = defineProps({ todo });
>     return `TodoItem${todoProps}[]`;
>   })
>   .join("");
> 
> return () => `ul[${todoItems}]`;
> ```

I see! But what if you want a dynamic list of items? Won't this just remain static?

Also, I have another little bug/quirk with list rendering. It renders a `,` between each list item as a separate text node. I'm assuming this for a similar reason to the non-breaking spaces, but I just thought I'd bring it to your attention.

**Comment by diogoneves07** [comment]
> > Avoid adding code that needs to go through some process inside the template, because the template will be checked for changes, which will cause the code inside it to be reprocessed.
> > Think of the template as just the place where you only display the results of some process:
> > ```js
> > const todoItems = todos
> >   .map((todo) => {
> >     const todoProps = defineProps({ todo });
> >     return `TodoItem${todoProps}[]`;
> >   })
> >   .join("");
> > 
> > return () => `ul[${todoItems}]`;
> > ```
> 
> I see! But what if you want a dynamic list of items? Won't this just remain static?
> 
> Also, I have another little bug/quirk with list rendering. It renders a `,` between each list item as a separate text node. I'm assuming this for a similar reason to the non-breaking spaces, but I just thought I'd bring it to your attention.

To have a dynamic list, you could do something like this:
```js
const todoItems = todos
  .map((todo) => {
    const todoProps = defineProps({ todo });
    return `TodoItem${todoProps}[]`;
  });

return () => `ul[${todoItems.join("")}]`;
```
If an item is added or changed in the list, the template will update the DOM. But this solution can affect performance in case of a big list because whenever the template is checked the list is converted to string

Before passing the list to the template you must convert it to a string, I believe this is the problem with the "," appearing in the document.

**Comment by ghost** [comment]
Ah, that makes sense! I will give it a go shortly. Is that the most performant way to do it though? I understand that it could cause performance problems.

**Comment by diogoneves07** [comment]
Currently, I believe that this is the cleanest way, and if your list is not a **"big list"** your application will not suffer with performance because the conversion from list to string is very fast.

Another solution would be to check if there was a change in the list "manually":
```js
const stringTodoItems = todoItems.join("");

return () =>
  `ul[${
    hasListChanged ? (stringTodoItems = todoItems.join("")) : stringTodoItems
  }]`;
```

In the near future, it may be interesting for the library to provide methods to deal with these situations in a clean way and without losing performance.

**Comment by ghost** [comment]
I agree! I think that would be a great thing to look at in the future. Maybe a helper to perform these computations or something similar. For now, the `join` method should be sound.

**Comment by diogoneves07** [comment]
> 

Thanks for your questions and suggestions! this helps improve the quality of  **Bemtv**

**Comment by ghost** [comment]
No worries! Glad to help. Also, does the list mapping re-render when items get added or removed? In theory, that wouldn't work because isn't the top level closure in a Component only run once?

**Comment by diogoneves07** [comment]
> No worries! Glad to help. Also, does the list mapping re-render when items get added or removed? In theory, that wouldn't work because isn't the top level closure in a Component only run once?

You're right, it's only possible to get the change in the list if you call the `join("")` method inside the template, so whenever the template is checked it will get the list with the current items

**Comment by ghost** [comment]
I know that this issue has been closed, but I am now having an issue with list rendering. You said that using `.join` will force it to recompute but the following code is static:

![image](https://user-images.githubusercontent.com/108161206/196589351-8813212b-4671-42b9-9bc8-521426b183f7.png)

Any ideas?

And when I put it directly into the template it causes an error like so:

![image](https://user-images.githubusercontent.com/108161206/196589458-fdfa3c1b-864e-45dd-8e89-36db07723fae.png)

**Comment by diogoneves07** [comment]
> I know that this issue has been closed, but I am now having an issue with list rendering. You said that using `.join` will force it to recompute but the following code is static:
> 
> ![image](https://user-images.githubusercontent.com/108161206/196589351-8813212b-4671-42b9-9bc8-521426b183f7.png)
> 
> Any ideas?
> 
> And when I put it directly into the template it causes an error like so:
> 
> ![image](https://user-images.githubusercontent.com/108161206/196589458-fdfa3c1b-864e-45dd-8e89-36db07723fae.png)

As I understand it, you want every time the `addTodo()` method is called a new item is added to the Map and with that you expect the template to update, am I right?

If so the problem is that the `addTodo()` method will only change the Map(`todos`) and the `todoItems` will not have any changes,
whenever the `addTodo()` method is used you should give a `todoItems.push(newTodo)`

**Comment by ghost** [comment]
> If so the problem is that the `addTodo()` method will only change the Map(`todos`) and the `todoItems` will not have any changes,
> whenever the `addTodo()` method is used you should give a `todoItems.push(newTodo)`

That would work, yeah. However, The client error at the bottom is something that I am still getting when I try to do that.

**Comment by diogoneves07** [comment]
> > If so the problem is that the `addTodo()` method will only change the Map(`todos`) and the `todoItems` will not have any changes,
> > whenever the `addTodo()` method is used you should give a `todoItems.push(newTodo)`
> 
> That would work, yeah. However, The client error at the bottom is something that I am still getting when I try to do that.

Could you add the complete code? So I can debug more clearly

If you can add the code in text so I can copy it
